version: '3.8'

services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee_management
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  frontend:
    build: 
        context: ./employee_management_frontend
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
        - "3000:8080"
    depends_on:
        - backend

  backend:
        build: 
            context: ./employee_management_backend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "5000:80"
        volumes: 
            - ./files:/files
        environment:
          - FILES_PATH=/files
        depends_on: 
            - db


volumes:
  db:
    driver: local
